server:
  port: 1111
eureka:
  instance:
    hostname: localhost
  client:
    prefer-ip-address: true
#    hostname: 192.168.2.103
    ip-address: localhost
    register-with-eureka: false     #不注册自己
    fetch-registry: false           #不检索服务
    service-url:
      default-zone: http://${eureka.client.ip-address}:${server.port}/eureka
security:
  basic:
    enabled: true
  user:
    name: wangcd
    password: 123456

    #http://${eureka.instance.hostname}:${server.port}/eureka